<?php
$ObjectManager= \Magento\Framework\App\ObjectManager::getInstance();
$context = $ObjectManager->get('Magento\Framework\App\Http\Context');
$validator = $ObjectManager->get('Lof\HidePrice\Model\Validator');
    
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
$customer_group_current = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_GROUP);
$helper = $this->helper("Lof\HidePrice\Helper\Data");
$maxWidth = $helper->getConfig('general/max_width');
$maxHeight = $helper->getConfig('general/max_height');
$minWidth = $helper->getConfig('general/min_width');
$minHeight = $helper->getConfig('general/min_height'); 
$_product = $block->getProduct();
$product_id = $_product->getId(); 
$validate = $validator->validate($product_id);  
$buttonTitle = __('Add to Cart');
$connection = $this->_resource->getConnection();
$table = $this->_resource->getTableName('lof_hideprice_product');
$where = ' entity_id = '.$product_id;
$select = 'SELECT * FROM ' . $table.' WHERE'.$where;

$hideprice = $connection->fetchAll($select);

$addtocart = '';
?>
<?php 
// $this->_scopeConfig->getValue('sectionName/groupName/fieldName');
//echo $block->getGeneralConfig(); 
?>
<?php if ($_product->isSaleable()): 
 $enabel_config = $block->getLayout()->createBlock('Nisl\Overrideproductdetail\Block\Overrideproductdetail');
    $nisl_enable = $enabel_config->getGeneralConfig();  

if ($nisl_enable == '1') {

$priority_one = $enabel_config->getPriorityOne();
$priority_two = $enabel_config->getPriorityTwo();
$priority_three = $enabel_config->getPriorityThree();

$warehouseCollectionFactory = $ObjectManager->get('\Amasty\MultiInventory\Model\ResourceModel\Warehouse\CollectionFactory');
$collection = $warehouseCollectionFactory->create();
$collection->addFieldToFilter('manage',1);
$collection->getSelect()->order('priority ASC');
if($collection->getSize()){
    $addtocart = "Out of Stock";
    foreach ($collection as $key => $value) {       
        $warehouse_id = $value['warehouse_id'];
        $priority = $value['priority'];       
        $stockItemRepository = $ObjectManager->get('\Amasty\MultiInventory\Api\WarehouseItemRepositoryInterface');
        $_productStock = $stockItemRepository->getByProductWarehouse($product_id,$warehouse_id);
        $_productStock_data = $_productStock->getData();
        $available_qty = intval($_productStock_data['available_qty']);
        if($available_qty > 0){
            $addtocart ='<div class="available_qty"><label class="label"><span>'.__('Available Qty :').'</span></label><div class="available_qty_value">'. intval($available_qty).'</div></div>';
            if($priority == 0){
                $addtocart .='<div class="free_shipping_label"><label class="label"><span>'.__('').'</span></label></div>';
            }else if($priority == 1){
                $addtocart .='<div class="free_shipping_label"><label class="label"><span>'.__($priority_one).'</span></label></div>';
            }else if($priority == 2){
                $addtocart .='<div class="free_shipping_label"><label class="label"><span>'.__($priority_two).'</span></label></div>';
            }
            else if($priority == 3){
                $addtocart .='<div class="free_shipping_label"><label class="label"><span>'.__($priority_three).'</span></label></div>';
            }
            break;
        }
    }
}

}
$addtocart .= '<div class="box-tocart">
    <div class="fieldset">';
        if ($block->shouldRenderQuantity()): 
        $addtocart .= '	
        <div class="field qty">
            <label class="label" for="qty"><span>'.__('Qty').'</span></label>
            <div class="control">
                <input type="number"
                   name="qty"
                   id="qty"
                   maxlength="12"
                   value="4"
                   title="'.__('Qty').'" class="input-text qty"
                   data-validate="'.$block->escapeHtml(json_encode($block->getQuantityValidators())).'"
                   />
            </div>
        </div>';
        endif;
        $addtocart .= '	
        <div class="actions">
            <button type="submit"
                    title="'.$buttonTitle.'"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span>'.$buttonTitle.'</span>
            </button>
            '.$block->getChildHtml('', true).'
        </div>
    </div>
</div>';
endif; 
if ((count($hideprice) > 0 || $validate) && $helper->getConfig('general/enable_module') == 1) {
    if(count($hideprice) > 0) {
	   $hideprice = $this->hideprice->getCollection()->addFieldToFilter('hideprice_id',$hideprice[0]['hideprice_id']);
    } elseif($validate) {
        $hideprice = $this->hideprice->getCollection()->addFieldToFilter('hideprice_id',$validate);
    }
 
	foreach ($hideprice as $key => $_hideprice) {
        
        $customer_group = json_decode($_hideprice->getCallforpriceCustomergroup(),true);
        $store_id = json_decode($_hideprice->getStoreId(),true);
        
		if($_hideprice->getIsActive() == 1 && (in_array($customer_group_current,$customer_group) == true  || ((in_array(0,$customer_group) ==false && $isLoggedIn ==false) || in_array(0,$customer_group) ==true)) && ((in_array($helper->getStoreId(), $store_id) == true) || (in_array(0,$store_id ) == true))) {
			echo "<p class='callforprice_text'><a href='#' class='btnfancy_hideprice_".$_product->getId()." action primary'>".$helper->filter($_hideprice->getCallforpriceText())."</a></p>";
			echo "<div id='hideprice_content_".$_product->getId()."' style='display: none;'>".$helper->filter($_hideprice->getContent())."</div>";
		} else {
			echo $addtocart;
		}
	
    ?>
        <script type="text/javascript">
            require([
                'jquery',
                'Lof_All/lib/fancybox/jquery.fancybox.pack'
                ], function($){
                jQuery(document).ready(function($) {
                    $('.formbuilder-form').prev().remove();
                    <?php if(!empty($helper->filter($_hideprice->getContent()))) { ?>
                    jQuery(".btnfancy_hideprice_<?php echo $_product->getId(); ?>").fancybox({
                        'href'   : '#hideprice_content_<?php echo $_product->getId(); ?>',
                        'titleShow'  : false,
                        'transitionIn'  : 'elastic',
                        'transitionOut' : 'elastic',
                        <?php if((int)$minWidth > 0) { echo "'minWidth' : ".$minWidth .","; } ?>
                        <?php if((int)$minHeight > 0) { echo "'minHeight' : ".$minHeight .","; } ?>
                        <?php if((int)$maxWidth > 0) { echo "'maxWidth' : ".$maxWidth .","; } ?>
                        <?php if((int)$maxHeight > 0) { echo "'maxHeight' : ".$maxHeight .","; } ?>
                    });
                    <?php } ?>
                    $('#hideprice_content_<?php echo $_product->getId(); ?>').find('#entity_id').val('<?php echo $_product->getId(); ?>');
                    $('#hideprice_content_<?php echo $_product->getId(); ?>').find('#hideprice_id').val('<?php echo $_hideprice->getHidepriceId(); ?>');
                });

            });
        </script>

<?php  
    }  
} else { 
	echo $addtocart;
}

?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

